In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("fake_news_train.csv")

In [3]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [4]:
#Drop Nan values
df=df.dropna()

In [5]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [6]:
## Get the Independent features
X=df.drop('label',axis=1)

In [7]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [8]:
#Dependent Feature
y=df['label']

In [9]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [10]:
import tensorflow as tf

In [11]:
tf.__version__

'2.11.0'

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [13]:
#vocabulary size
voc_size=5000

# Onehot Representation

In [14]:
messages=X.copy()

In [15]:
messages.reset_index(inplace=True)

In [16]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [17]:
import nltk
import re
from nltk.corpus import stopwords

### Data Preprocessing

In [18]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [19]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [20]:
one_hot_repr=[one_hot(words,voc_size) for words in corpus]

In [21]:
one_hot_repr

[[3354, 338, 739, 2967, 2365, 2478, 2482, 2941, 451, 3972],
 [1151, 1026, 94, 359, 2845, 2762, 4291],
 [34, 1535, 307, 2172],
 [2734, 3427, 4381, 1774, 72, 4138],
 [2072, 2845, 4601, 3507, 3602, 3380, 2845, 2046, 2485, 1669],
 [1979,
  1269,
  2620,
  1776,
  2243,
  3551,
  2217,
  2562,
  801,
  4390,
  4644,
  4587,
  3500,
  2012,
  4291],
 [3866, 4038, 1467, 4971, 3604, 1726, 2649, 1985, 264, 4924, 3461],
 [1078, 1546, 436, 3746, 1092, 2431, 3551, 3343, 264, 4924, 3461],
 [3754, 636, 2911, 4730, 38, 3278, 611, 95, 3551, 2312],
 [4870, 361, 4060, 2674, 3273, 1288, 76, 1337],
 [2385, 1363, 4098, 3850, 3854, 3099, 1194, 4131, 4974, 4150, 2877],
 [1774, 4582, 2365, 3278, 3551, 1092],
 [437, 1639, 3552, 329, 512, 3977, 3425, 2069, 2915],
 [4746, 3884, 3510, 4540, 3343, 2336, 3144, 264, 4924, 3461],
 [3883, 4304, 2484, 4877, 4715, 264, 4924, 3461],
 [2410, 1203, 934, 227, 3013, 3049, 2630, 680, 3018, 2826],
 [534, 3283, 1026],
 [3042, 4441, 1270, 3693, 3551, 3417, 556, 4291],
 [4957, 30

### Embedding Representation

In [22]:
sent_length=20
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [23]:
len(embedded_docs)

18285

In [24]:
embedded_docs[0],embedded_docs[2346]

(array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3354,
         338,  739, 2967, 2365, 2478, 2482, 2941,  451, 3972]),
 array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 3101, 3380, 4782, 3417,  264, 4924, 3461]))

## Creating Model

In [25]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(5,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 5)                 505       
                                                                 
Total params: 256,905
Trainable params: 256,905
Non-trainable params: 0
_________________________________________________________________


In [27]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:
x_final.shape,y_final.shape

((18285, 20), (18285,))

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=42)

In [ ]:
## Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=30,batch_size=64)

Epoch 1/100
200/200 [==============================] - 7s 25ms/step - loss: 0.3333 - accuracy: 0.8429 - val_loss: 0.1966 - val_accuracy: 0.9158
Epoch 2/100
200/200 [==============================] - 5s 25ms/step - loss: 0.1388 - accuracy: 0.9455 - val_loss: 0.2053 - val_accuracy: 0.9182
Epoch 3/100
200/200 [==============================] - 4s 21ms/step - loss: 0.0974 - accuracy: 0.9623 - val_loss: 0.2375 - val_accuracy: 0.9202
Epoch 4/100
200/200 [==============================] - 5s 23ms/step - loss: 0.0725 - accuracy: 0.9745 - val_loss: 0.2470 - val_accuracy: 0.9143
Epoch 5/100
200/200 [==============================] - 5s 24ms/step - loss: 0.0512 - accuracy: 0.9827 - val_loss: 0.3055 - val_accuracy: 0.9202
Epoch 6/100
200/200 [==============================] - 4s 22ms/step - loss: 0.0378 - accuracy: 0.9880 - val_loss: 0.2588 - val_accuracy: 0.9163
Epoch 7/100
200/200 [==============================] - 5s 24ms/step - loss: 0.0242 - accuracy: 0.9931 - val_loss: 0.3389 - val_accuracy:

## Performance Metrics and Accuracy

In [36]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

172/172 [==============================] - 1s 4ms/step


In [37]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [38]:
y_test

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [39]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [40]:
confusion_matrix(y_test,y_pred)

array([[2817,  290],
       [ 177, 2202]], dtype=int64)

In [41]:
accuracy_score(y_test,y_pred)

0.9148742253007656